LostTags/urls.py
from django.contrib import admin 
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('', include('droptag.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
]
 

droptag/urls.py
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 24 12:25:09 2020
@author: truet
"""
from django.urls import path
from django.conf.urls import url
from . import views
from .views import Home, TagDetailView, CreateTag, UpdateTag, DeleteTag, AllTags, ViewProfile, register, ChangePasswordView

urlpatterns = [
    path('', Home.as_view(), name='homepage'),
    path('register/', views.register, name='register'),
    path('alltags/', AllTags.as_view(), name='alltags'),
    path('tag/<int:pk>', TagDetailView.as_view(), name='tag_display'),
    path("create_tag/", CreateTag.as_view(), name='create_tag'),
    path("tag/update/<int:pk>", UpdateTag.as_view(), name='update_tag'),
    path("tag/delete/<int:pk>", DeleteTag.as_view(), name='delete_tag'),
    path(r'^(?P<user>[-_\w]+)/detail/$', views.ViewProfile, name='view_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('password/', ChangePasswordView.as_view(), name='change_password'),
]

droptag/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver


PLATFORM_CHOICES = (
        ("PSN", "PlayStation"),
        ("XB", "Xbox"),
        ("DC", "Discord"),
        ("STM", "Steam"),
        )

class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE) 
    name = models.CharField(max_length=200, blank=True) 
    steam_id = models.CharField(max_length=200, blank=True)
    psn_id = models.CharField(max_length=200, blank=True) 
    xbox_id = models.CharField(max_length=200, blank=True) 
    discord_id = models.CharField(max_length=45, blank=True) 
    bio = models.TextField(blank=True)

    def __str__(self):
        return str(self.user)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()



class tag(models.Model): 
    user = models.ForeignKey(User, 
                        default = 1,   
                        on_delete = models.CASCADE 
                        )
    
    platform = models.CharField(
        default='STM',
        max_length=32,
        choices=PLATFORM_CHOICES)
    username = models.CharField(max_length=50)
    id_link = models.CharField(max_length=200, blank=True)
    time_met = models.DateField()
    note = models.TextField(blank=True)
    date_filled = models.DateTimeField(auto_now_add=True)
        
    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        return reverse('tag_display', args=[str(self.id)])

droptag/forms.py
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 26 20:40:28 2020

@author: truet
"""
from django import forms 
from .models import tag, UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
  
class tagForm(forms.ModelForm): 
    class Meta: 
        model = tag
        fields = ['platform',
        'username', 
        'id_link',  
        'time_met',
        'note'
        ]

        labels = {
            'time_met':'Date Met'
        }

        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Steam, Xbox, PSN, or Discord Username'}),
            'id_link': forms.TextInput(attrs={'placeholder':'Link To Account (optional)'}),
            'time_met': forms.DateInput(attrs={'placeholder':'When Did You Meet Them?'}),
            'note': forms.Textarea(attrs={'placeholder':'Extra Information (optional)'}),
            }
        

class UpdateTagForm(forms.ModelForm): 
    class Meta: 
        model = tag
        fields = [
        'username', 
        'id_link',  
        'time_met',
        'note'
        ]

        labels = {
            'time_met':'Date Met'
        }

        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Steam, Xbox, PSN, or Discord Username'}),
            'id_link': forms.TextInput(attrs={'placeholder':'Link To Account (optional)'}),
            'time_met': forms.DateInput(attrs={'placeholder':'When Did You Meet Them?'}),
            'note': forms.Textarea(attrs={'placeholder':'Extra Information (optional)'}),
            }
         


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
        }
        fields = ['username', 'password1', 'password2']
        
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'}),
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
            }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name',
                  'steam_id', 
                  'psn_id', 
                  'xbox_id', 
                  'discord_id', 
                  'bio'
                  ]
        
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'steam_id': forms.TextInput(attrs={'class':'form-control'}),
            'psn_id': forms.TextInput(attrs={'class':'form-control'}),
            'xbox_id': forms.TextInput(attrs={'class':'form-control'}),
            'discord_id': forms.TextInput(attrs={'class':'form-control'}),
            'bio': forms.Textarea(attrs={'class':'form-control'}),
            }



class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    new_password2 = forms.CharField(label='New Password Confirmation', widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    
    
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')



       
class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['steam_id', 
                  'psn_id', 
                  'xbox_id', 
                  'discord_id', 
                  'bio'
                  ]
        
        widgets = {
            'steam_id': forms.TextInput(attrs={'class':'form-control'}),
            'psn_id': forms.TextInput(attrs={'class':'form-control'}),
            'xbox_id': forms.TextInput(attrs={'class':'form-control'}),
            'discord_id': forms.TextInput(attrs={'class':'form-control'}),
            'bio': forms.Textarea(attrs={'class':'form-control'}),
            }

droptag/views.py
from .models import tag, UserProfile
from .forms import tagForm, UpdateTagForm, UserProfileForm, UserRegisterForm, EditUserProfileForm, PasswordChangingForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.views import PasswordChangeView
import json
# Create your views here.


class Home(ListView):
    model = tag
    template_name = 'index.html'
    queryset = tag.objects.order_by('-date_filled')[0:5]
    
    
class AllTags(ListView):
    model = tag
    template_name = 'alltags.html'
    queryset = tag.objects.order_by('-date_filled')


class TagDetailView(DetailView):
    model = tag
    template_name = 'tag.html'


class CreateTag(LoginRequiredMixin, CreateView):
    login_url = '/users/login'
    redirect_field_name = 'login'
    
    model = tag
    form_class = tagForm
    template_name = "createtag.html"
    
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class UpdateTag(LoginRequiredMixin, UpdateView):
    login_url = '/users/login'
    redirect_field_name = 'login'
    
    model = tag
    form_class = UpdateTagForm
    template_name = 'update_tag.html'


class DeleteTag(LoginRequiredMixin, DeleteView):
    login_url = '/users/login'
    redirect_field_name = 'login'
    
    model = tag
    template_name = "deletetag.html"
    success_url = reverse_lazy('homepage')


def ViewProfile(request, user):
    profile = UserProfile.objects.get(user=user)
    return render(request, 'viewprofile.html', {'profile':profile})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        p_reg_form = UserProfileForm(request.POST)
        if form.is_valid() and p_reg_form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            p_reg_form = UserProfileForm(request.POST, instance=user.userprofile)
            p_reg_form.full_clean()
            p_reg_form.save()
            messages.info(request, "Thanks for registering. You are now logged in.")
            user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, user)
            return HttpResponseRedirect(reverse('homepage'))
    else:
        form = UserRegisterForm()
        p_reg_form = UserProfileForm()
        
    context = {
        'form': form,
        'p_reg_form': p_reg_form
    }

    return render(request, 'registration/register.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        profile_form = EditUserProfileForm(request.POST, instance=request.user.userprofile)

        if profile_form.is_valid():
            custom_form = profile_form.save(False)
            custom_form.save()
            return HttpResponseRedirect(reverse('homepage'))
    else:
        profile_form = EditUserProfileForm(instance=request.user.userprofile)
        args = {}
        args['profile_form'] = profile_form
        return render(request, 'edit_profile.html', args)


class ChangePasswordView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('edit_profile')
    template_name = 'change-password.html'

droptag/templates/alltags.html
{% extends 'base.html' %} 
{% block title %} Search Tag {% endblock %}
{% block content %} {% load static %}

{% block css %}
<head>
  <link rel="stylesheet" href="{% static 'style.css' %}" />
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css">
</head>
{% endblock css %}

<h1>All Tags</h1>
<br /><br/>

<table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
      <tr>
        <th>Username</th>
        <th>Platform</th>
        <th>Date Met</th>
      </tr>
  </thead>
  <tbody>
    {% for tag in object_list %}
    <tr>
      <td data-title="Username">
        <a href="{% url 'tag_display' tag.pk %}">{{ tag.username }}</a>
      </td>
      <td data-title="Platform">
        {{ tag.get_platform_display }} 
      </td>
      <td data-title="Link">{{ tag.time_met }}</td>
    </tr>
    {% endfor %}
  </table>

<!--
<table class="highlight" >
  <thead>
    <tr>
      <th>Username</th>
      <th>Platform</th>
      <th>Date Met</th>
    </tr>
  </thead>
  <tbody>
    {% for tag in object_list %}
    <tr>
      <td data-title="Username">
        <a href="{% url 'tag_display' tag.pk %}">{{ tag.username }}</a>
      </td>
      <td data-title="Platform">
        {{ tag.get_platform_display }} 
      </td>
      <td data-title="Link">{{ tag.time_met }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br />
<br />
-->

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

<script>
  $(document).ready(function() {
    $('#example').DataTable();
  } );
</script>
{% endblock javascript %}

{% endblock %}

droptag/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- navbar css below -->
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block css %}
    {% endblock css %}
  </head>
    <title>{% block title %} Home {% endblock %}</title>
  </head>
  <body>
    <!-- nav bar -->
    <nav id="scanfcode" class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" id="toogle-button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
           <span class="glyphicon glyphicon-menu-hamburger"></span>                     
          </button>
          <a id="logo" class="navbar-brand" href="{% url 'homepage' %}">User Tags</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul id="link" class="nav navbar-nav navbar-left">
            <li class="dropdown" id="first-link"><a class="nav-link" href="{% url 'create_tag' %}">Make A Tag</a></li>
            <li class="dropdown" id="first-link"><a class="nav-link" href="{% url 'alltags' %}">All Tags</a>
          </ul>
          <ul id="link" class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
             <li class="dropdown" id="first-link">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'edit_profile' %}" style='font-size: 12px;'>Edit Profile</a></li>
                <li><a href="{% url 'logout' %}" style='font-size: 12px;'>Logout</a></li>
              </ul>
            </li>
            {% else %}
            <li><a href="{% url 'login' %}">Sign In</a></li>
            <li id="button-link"><a href="{% url 'register' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!---->
    <br />
    <div class="container" id="content">{% block content %} {% endblock %}</div>
    <br/>

    <!-- jquey/bootstrap/navbar/table scripts -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

droptag/templates/change-password.html
{% extends 'base.html' %}

{% block title %} Change Password {% endblock %}

{% block content %}

{% load static %}
{% load materializecss %}
{% block css %}
<header>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
</header>
{% endblock css %}

<h1 style="font-size: 30px;" id="right-move">Change Password</h1>
<hr>
<br/>
<form method="POST">
  {% csrf_token %}
  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s8">
          {{ form.old_password|materializecss:"icon=lock" }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s8">
          {{ form.new_password1|materializecss:"icon=lock_open" }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s8">
          {{ form.new_password2|materializecss:"icon=lock_outline" }}
        </div>
      </div>
      <div class="row">
        <div class="col s8">
          <ul style="font-size: 15px;" id="pwd-change-field">
            <li>Your password can’t be too similar to your other personal information.</li>
            
            <li>Your password must contain at least 8 characters.</li>
            
            <li>Your password can’t be a commonly used password.</li>
            
            <li>Your password can’t be entirely numeric.</li>
        </ul>
        </div>
      </div>
      </div>
      <br/>
      <button class="btn btn-primary" id="right-move">Submit</button>
      <br/><br/>
    </form>
  </div>
</form>

<br>
<br/>

{% block javascript %}
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  // Initialize materialize data picker
  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});

  $('select').formSelect();
  $('select').material_select();
});
</script>
{% endblock javascript %}

{% endblock %}

droptag/templates/createtag.html
{% extends 'base.html' %}

{% block title %} Make A Tag {% endblock %}

{% block content %}

{% load static %}
{% load materializecss %}

{% block css %}
<header>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
</header>
{% endblock css %}


<h1 style="font-size: 30px;" id="right-move">Submit A Custom Tag</h1>
<hr>
<br>
<form method="POST">
  {% csrf_token %}
  <form class="col s12">
    <div class="row">
      <div class="input-field col s9">
        {{ form.username|materializecss:"icon=perm_contact_calendar" }}
      </div>
      <div class="input-field col s3 offset-9">
        {{ form.platform|materializecss }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s9">
        {{ form.id_link|materializecss:"icon=insert_link" }}
      </div>
      <div class="input-field col s3 offset-9">
        {{ form.time_met|materializecss }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        {{ form.note|materializecss:"icon=create" }}
      </div>
    </div>
    <button class="btn btn-primary" style="float:left" id="right-move">Submit</button>
  </form>
</form>
<br/><br/>



{% block javascript %}
<script>
    var name = "{{ user.id }}";
    document.getElementById("user_js").value = name;
</script>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  // Initialize materialize data picker
  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
  $('select').formSelect();

});
</script>
{% endblock javascript %}


{% endblock %}

droptag/templates/deletetag.html
{% extends 'base.html' %}

{% block title %} Delete Tag {% endblock %}

{% block content %}

{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />
    <!-- navbar css below -->
    <link
      href="https://fonts.googleapis.com/css?family=Encode+Sans"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
</head>

<h1><i>{{ tag.username }}</i></h1>
<p class="font-weight-light"><b>Platform:</b> {{ tag.get_platform_display }} </p>
<hr>
<br/>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {% if tag.id_link %}
            <b>Links:</b> {{ tag.id_link }}<br/>
        {% endif %}
        {% if tag.time_met %}
            <b>Last Seen:</b> {{ tag.time_met }}<br/>
        {% endif %}
        {% if tag.note %}
            <b>Note:</b> {{ tag.note }}<br/>
        {% endif %}
        <small>Date Filled: {{ tag.date_filled }}<br/>
</div>
<br/>
<strong>Delete this tag? This can't be undone.</strong><br/>
<br/><br/>
<a href="{% url 'tag_display' tag.pk %}" class="btn btn-primary">Back</a> <button class="btn btn-danger">Delete</button>

{% endblock %}

    

droptag/templates/index.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %}



<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- navbar css below -->
  <link href="https://fonts.googleapis.com/css?family=Encode+Sans" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>


{% load materializecss %}

<h2 style="font-size: 30px;">Find Old Friends, From Anywhere</h2>
<hr/>

Have you been thinking about that online friend who last logged in years ago? 
File a custom tag with their long lost Steam, Playstation, Xbox, or Discord username along with any
relevant information and they'll find themselves in our database wth an easy search.
<br/><br/>
<br/>

<h2 style="font-size: 30px;">Recent Tags</h2>
<hr/>

<!-- Table starts here -->
<table class="highlight" >
  <thead>
    <tr>
      <th>Username</th>
      <th>Platform</th>
      <th>Date Met</th>
    </tr>
  </thead>
  <tbody>
    {% for tag in object_list %}
    <tr>
      <td data-title="Username">
        <a href="{% url 'tag_display' tag.pk %}">{{ tag.username }}</a>
      </td>
      <td data-title="Platform">
        {{ tag.get_platform_display }} 
      </td>
      <td data-title="Link">{{ tag.time_met }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br />

{% endblock content %}

droptag/templates/tag.html
{% extends 'base.html' %} {% block title %}Tag: {{ tag.username }}{% endblock %}
{% block content %}

{% load static %}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  />
  <!-- navbar css below -->
  <link
    href="https://fonts.googleapis.com/css?family=Encode+Sans"
    rel="stylesheet"
  />
  <link rel="stylesheet" href="{% static 'style.css' %}" />
</head>

<h1><i>{{ tag.username }}</i></h1>
<p class="font-weight-light"><b>Platform:</b> {{ tag.get_platform_display }}</p>
<hr />
<br />
<b>Tag Owner:</b
><a href="{% url 'view_profile' tag.user.id %}"> {{ tag.user }}</a><br />
{% if tag.id_link %}
<b>Links:</b> {{ tag.id_link }}<br />
{% endif %} {% if tag.time_met %}
<b>Last Seen:</b> {{ tag.time_met }}<br />
{% endif %} {% if tag.note %}
<b>Note:</b> {{ tag.note }}<br />
{% endif %}

<small
  >Date Filled: {{ tag.date_filled }}<br />
  {% if user.is_authenticated %} {% if user.id == tag.user.id %}
  <small
    ><a href="{% url 'update_tag' tag.pk %}">(Edit)</a>
    <a href="{% url 'delete_tag' tag.pk %}">(Delete)</a>
  </small>
  {% endif %} {% endif %}
  <br /><br />
  <a href="{% url 'alltags' %}" class="btn btn-primary">Back</a>
  <br/>
</small>
<br/>
  {% endblock %}

droptag/templates/update_tag.html
{% extends 'base.html' %}

{% block title %} Update A Tag {% endblock %}

{% block content %}

{% load static %}
{% load materializecss %}

{% block css %}
<header>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
</header>
{% endblock css %}

<h1 style="font-size: 30px;" id="right-move">Update Tag</h1>
<hr>
<br>
<form method="POST">
  {% csrf_token %}
  <form class="col s12">
    <div class="row">
      <div class="input-field col s9">
        {{ form.username|materializecss:"icon=perm_contact_calendar" }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s9">
        {{ form.id_link|materializecss:"icon=insert_link" }}
      </div>
      <div class="input-field col s3 offset-9">
        {{ form.time_met|materializecss }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        {{ form.note|materializecss:"icon=create" }}
      </div>
    </div>
    <button class="btn btn-primary" style="float:left" id="right-move">Submit</button>
  </form>
</form>
<br/>
<br>

{% block javascript %}
<script>
    var name = "{{ user.id }}";
    document.getElementById("user_js").value = name;
</script>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  // Initialize materialize data picker
  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
  $('select').formSelect();

});
</script>
{% endblock javascript %}
    
{% endblock %}